# Generated by Django 5.2.8 on 2025-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_created_by_task_priority_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
