# Generated by Django 5.2.8 on 2026-02-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_activtiylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activtiylog',
            options={},
        ),
        migrations.RemoveField(
            model_name='activtiylog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='activtiylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
    ]
