# Generated by Django 5.2.8 on 2026-02-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_title_project_name_and_more'),
        ('tasks', '0009_alter_activtiylog_options_remove_activtiylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.project'),
        ),
    ]
